### ISSUE TITLE
FATAL EXCEPTION: AsyncTask #1

### ISSUE THREAD

**Issue by chaoscalm** [apsun/NekoSMS#101]
```
FATAL EXCEPTION: AsyncTask #1
Process: com.crossbowffs.nekosms, PID: 8579
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at androidx.loader.content.ModernAsyncTask$2.done(SourceFile:48)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 12 to 11
	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:547)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:413)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
	at com.crossbowffs.nekosms.provider.DatabaseProvider.getDatabase(SourceFile:12)
	at com.crossbowffs.nekosms.provider.DatabaseProvider.query$com$crossbowffs$nekosms$widget$AutoContentProvider(SourceFile:1)
	at com.crossbowffs.nekosms.provider.DatabaseProvider.query(Unknown Source:3)
	at android.content.ContentProvider.query(ContentProvider.java:1620)
	at android.content.ContentProvider.query(ContentProvider.java:1716)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:295)
	at android.content.ContentResolver.query(ContentResolver.java:1229)
	at android.content.ContentResolver.query(ContentResolver.java:1161)
	at androidx.core.content.ContentResolverCompat$Api16Impl.query(Unknown Source:0)
	at androidx.loader.content.CursorLoader.onLoadInBackground(SourceFile:51)
	at androidx.loader.content.ModernAsyncTask$1.call(SourceFile:19)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

**Comment by chaoscalm** [comment]
It is better don't dowgrade app from 0.23 to 0.22
