### ISSUE TITLE
Neko SMS module doesn't filter sms

### ISSUE THREAD

**Issue by raamee** [apsun/NekoSMS#41]
Hi,

It's not filtering SMS. I guess it's because it not always in memory?. I checked in running process and it's not there.

But when I open neko SMS app once, it works untill I lock the screen.

Device is OnePlus 5
System less xposed via magisk.

---

- Device: OnePlus 5
- Android version:  7.1.1
- Xposed version: 88.2
- NekoSMS version: 0.15.0

Xposed logs:

```
12-03 15:26:00.061 I/Xposed  ( 6265): -----------------
12-03 15:26:00.061 I/Xposed  ( 6265): Starting Xposed version 88.2 (Systemless by topjohnwu), compiled for SDK 25
12-03 15:26:00.061 I/Xposed  ( 6265): Device: ONEPLUS A5000 (OnePlus), Android version 7.1.1 (SDK 25)
12-03 15:26:00.061 I/Xposed  ( 6265): ROM: ONEPLUS A5000_23_171031
12-03 15:26:00.061 I/Xposed  ( 6265): Build fingerprint: OnePlus/OnePlus5/OnePlus5:7.1.1/NMF26X/10171617:user/release-keys
12-03 15:26:00.061 I/Xposed  ( 6265): Platform: arm64-v8a, 64-bit binary, system server: yes
12-03 15:26:00.061 I/Xposed  ( 6265): SELinux enabled: yes, enforcing: yes
12-03 15:26:00.076 I/Xposed  ( 6265): -----------------
12-03 15:26:00.076 I/Xposed  ( 6265): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
12-03 15:26:00.294 I/Xposed  ( 6265): Detected ART runtime
12-03 15:26:00.295 I/Xposed  ( 6265): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
12-03 15:26:00.386 I/Xposed  ( 6265): Loading modules from /data/app/kmod.xposed-1/base.apk
12-03 15:26:00.400 I/Xposed  ( 6265):   Loading class kmod.xposed.g
12-03 15:26:00.432 I/Xposed  ( 6265): Loading modules from /data/app/com.crossbowffs.nekosms-1/base.apk
12-03 15:26:00.444 I/Xposed  ( 6265):   Loading class com.crossbowffs.nekosms.xposed.SmsHandlerHook
12-03 15:26:00.446 I/Xposed  ( 6265):   Loading class com.crossbowffs.nekosms.xposed.XposedUtilsHook
12-03 15:26:00.446 I/Xposed  ( 6265): Loading modules from /data/app/tw.fatminmin.xposed.minminguard-1/base.apk
12-03 15:26:00.534 I/Xposed  ( 6265):   Loading class tw.fatminmin.xposed.minminguard.Main
12-03 15:26:00.572 I/Xposed  ( 6265): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
12-03 15:26:00.587 I/Xposed  ( 6265):   Loading class ma.wanam.youtubeadaway.Xposed
12-03 15:26:00.588 I/Xposed  ( 6265):   Loading class ma.wanam.youtubeadaway.ResXposed
12-03 15:26:06.551 I/Xposed  ( 7202): NekoSMS: NekoSMS initializing...
12-03 15:26:06.551 I/Xposed  ( 7202): NekoSMS: Phone manufacturer: OnePlus
12-03 15:26:06.551 I/Xposed  ( 7202): NekoSMS: Phone model: ONEPLUS A5000
12-03 15:26:06.551 I/Xposed  ( 7202): NekoSMS: Android version: 7.1.1
12-03 15:26:06.551 I/Xposed  ( 7202): NekoSMS: Xposed bridge version: 88
12-03 15:26:06.552 I/Xposed  ( 7202): NekoSMS: NekoSMS version: 0.15.0 (31)
12-03 15:26:06.552 I/Xposed  ( 7202): NekoSMS: Hooking InboundSmsHandler constructor for Android v24+
12-03 15:26:06.559 I/Xposed  ( 7202): NekoSMS: Hooking dispatchIntent() for Android v23+
12-03 15:26:06.560 I/Xposed  ( 7202): NekoSMS: NekoSMS initialization complete!
12-03 15:26:06.809 I/Xposed  ( 7202): NekoSMS: Registering SMS filter content observer
12-03 15:26:06.810 I/Xposed  ( 7202): NekoSMS: Registering app package state receiver
12-03 15:26:06.811 I/Xposed  ( 7202): NekoSMS: Checking if we have OP_WRITE_SMS permission
12-03 15:26:06.812 I/Xposed  ( 7202): NekoSMS: Already have OP_WRITE_SMS permission
12-03 15:26:22.643 E/Xposed  ( 7756): Zygote service is not accessible from PID 7756, UID 10013
12-03 15:26:22.646 E/Xposed  ( 7756): Zygote service is not accessible from PID 7756, UID 10013
12-03 15:26:22.647 E/Xposed  ( 7756): Zygote service is not accessible from PID 7756, UID 10013
12-03 15:26:22.648 E/Xposed  ( 7756): Zygote service is not accessible from PID 7756, UID 10013
12-03 15:26:22.650 E/Xposed  ( 7756): Zygote service is not accessible from PID 7756, UID 10013
12-03 15:26:22.651 E/Xposed  ( 7756): Zygote service is not accessible from PID 7756, UID 10013
12-03 15:26:22.670 E/Xposed  ( 7756): Zygote service is not accessible from PID 7756, UID 10013
12-03 15:26:22.672 E/Xposed  ( 7756): Zygote service is not accessible from PID 7756, UID 10013
12-03 15:26:22.672 E/Xposed  ( 7756): Zygote service is not accessible from PID 7756, UID 10013
12-03 15:26:22.673 E/Xposed  ( 7756): Zygote service is not accessible from PID 7756, UID 10013
12-03 15:26:35.829 I/Xposed  ( 8012): KMod: DIE
12-03 15:27:03.960 I/Xposed  (10075): KMod: DIE
12-03 15:27:26.700 E/Xposed  ( 7202): NekoSMS: Failed to read preference: pref_enable
12-03 15:27:26.705 I/Xposed  ( 7202): NekoSMS: Received a new SMS message
12-03 15:27:26.708 E/Xposed  ( 7202): NekoSMS: Failed to read preference: pref_whitelist_contacts
12-03 15:27:26.708 I/Xposed  ( 7202): NekoSMS: Cached SMS filters dirty, loading from database
12-03 15:27:26.711 E/Xposed  ( 7202): NekoSMS: Failed to load SMS filters (queryAll returned null)
12-03 15:27:26.711 I/Xposed  ( 7202): NekoSMS: Allowed message (matched whitelist or no matching rules)
12-03 15:27:36.651 I/Xposed  (10656): NekoSMS: Hooking Xposed module status checker
12-03 15:27:43.589 I/Xposed  ( 7202): NekoSMS: SMS filter database updated, marking cache as dirty
12-03 15:28:09.678 I/Xposed  ( 7202): NekoSMS: Received a new SMS message
12-03 15:28:09.685 I/Xposed  ( 7202): NekoSMS: Cached SMS filters dirty, loading from database
12-03 15:28:09.698 I/Xposed  ( 7202): NekoSMS: Blocked message (matched blacklist)
12-03 15:28:09.727 I/Xposed  ( 7202): NekoSMS: Removing raw SMS data from database for Android v24+
12-03 15:28:09.744 I/Xposed  ( 7202): NekoSMS: Notifying completion of SMS broadcast
12-03 15:33:32.879 E/Xposed  (12558): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
12-03 15:33:32.879 E/Xposed  (12558): 	at kmod.xposed.p$1.beforeHookedMethod(Unknown Source)
12-03 15:33:32.879 E/Xposed  (12558): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
12-03 15:33:32.879 E/Xposed  (12558): 	at com.whatsapp.HomeActivity.onCreate(<Xposed>)
12-03 15:33:32.879 E/Xposed  (12558): 	at android.app.Activity.performCreate(Activity.java:6743)
12-03 15:33:32.879 E/Xposed  (12558): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
12-03 15:33:32.879 E/Xposed  (12558): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2715)
12-03 15:33:32.879 E/Xposed  (12558): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2848)
12-03 15:33:32.879 E/Xposed  (12558): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-03 15:33:32.879 E/Xposed  (12558): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
12-03 15:33:32.879 E/Xposed  (12558): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-03 15:33:32.879 E/Xposed  (12558): 	at android.os.Looper.loop(Looper.java:154)
12-03 15:33:32.879 E/Xposed  (12558): 	at android.app.ActivityThread.main(ActivityThread.java:6334)
12-03 15:33:32.879 E/Xposed  (12558): 	at java.lang.reflect.Method.invoke(Native Method)
12-03 15:33:32.879 E/Xposed  (12558): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-03 15:33:32.879 E/Xposed  (12558): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-03 15:33:32.879 E/Xposed  (12558): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
12-03 15:43:17.435 I/Xposed  (14103): NekoSMS: Hooking Xposed module status checker

```

**Comment by apsun** [comment]
Sounds like @38

NekoSMS is actually not supposed to always run in the background, so not having the background process is normal. However, task blocker apps do interfere with it. OxygenOS has a built-in task blocker; try adding NekoSMS to the whitelist.

**Comment by raamee** [comment]
Awesome. That fixed it. :) Thank you.

**Comment by Burnzero** [comment]
Actually, I want to re-open this:

There is some senders with name AT650011 and AT650003 from my carrier. Its all just promotional spam messages.

I created a rule to block this. The rule is:

if sender contains AT6500 - case insensitive.

This should block, but it isn't blocking.

In Xposed log, I just get:

```
12-05 12:21:26.711 I/Xposed  ( 7202): NekoSMS: Allowed message (matched whitelist or no matching rules)
```

But if I have the same condition to body, then it works. What could be the issue?

Thanks.
