### ISSUE TITLE
OnePlus 5設備中將NekoSMS從最近應用列表中移除後，短信攔截功能失效

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [apsun/NekoSMS#52]
如果不在最近應用列表中將程序移除，短信攔截功能是正常的。
檢查過設置，設置中的“多任務清除方式”是“普通清除”，並不會殺死後臺進程。
不知道是程序問題還是系統的問題，希望能夠解決。

關於Xposed，我曾經試過直接安裝，但似乎表面上顯示已啓用，其實並沒有任何實際效果，在嘗試Magisk的版本後才可以正常使用。

---

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device: OnePlus 5
- Android version: 8.1 (OxygenOS 5.1.4)
- Xposed version: 90.2-beta3 (Magisk systemless)
- NekoSMS version: 0.17.0

Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:

```
08-17 11:25:04.813 I/Xposed  ( 1877): NekoSMS: Hooking Xposed module status checker
08-17 11:25:06.811 E/Xposed  ( 2716): NekoSMS: Failed to read preference: pref_enable
08-17 11:25:06.811 E/Xposed  ( 2716): com.crossbowffs.remotepreferences.RemotePreferenceAccessException: query() failed or returned null cursor
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.crossbowffs.remotepreferences.RemotePreferences.query(RemotePreferences.java:156)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.crossbowffs.remotepreferences.RemotePreferences.querySingle(RemotePreferences.java:175)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.crossbowffs.remotepreferences.RemotePreferences.getBoolean(RemotePreferences.java:99)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.getBooleanPref(SmsHandlerHook.java:171)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.beforeDispatchIntentHandler(SmsHandlerHook.java:202)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.access$100(SmsHandlerHook.java:32)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook$DispatchIntentHook.beforeHookedMethod(SmsHandlerHook.java:55)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.dispatchIntent(<Xposed>)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.dispatchSmsDeliveryIntent(InboundSmsHandler.java:1233)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.-wrap4(Unknown Source:0)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler$CarrierServicesSmsFilterCallback.onFilterComplete(InboundSmsHandler.java:1472)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.android.internal.telephony.CarrierServicesSmsFilter$FilterAggregator.onFilterComplete(CarrierServicesSmsFilter.java:287)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at com.android.internal.telephony.CarrierServicesSmsFilter$CarrierSmsFilterCallback.onFilterComplete(CarrierServicesSmsFilter.java:244)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at android.service.carrier.ICarrierMessagingCallback$Stub.onTransact(ICarrierMessagingCallback.java:55)
08-17 11:25:06.811 E/Xposed  ( 2716): 	at android.os.Binder.execTransact(Binder.java:714)
08-17 11:25:06.813 I/Xposed  ( 2716): NekoSMS: Received a new SMS message
08-17 11:25:06.814 E/Xposed  ( 2716): NekoSMS: Failed to read preference: pref_verbose_logging
08-17 11:25:06.814 E/Xposed  ( 2716): com.crossbowffs.remotepreferences.RemotePreferenceAccessException: query() failed or returned null cursor
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.crossbowffs.remotepreferences.RemotePreferences.query(RemotePreferences.java:156)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.crossbowffs.remotepreferences.RemotePreferences.querySingle(RemotePreferences.java:175)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.crossbowffs.remotepreferences.RemotePreferences.getBoolean(RemotePreferences.java:99)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.getBooleanPref(SmsHandlerHook.java:171)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.beforeDispatchIntentHandler(SmsHandlerHook.java:211)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.access$100(SmsHandlerHook.java:32)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook$DispatchIntentHook.beforeHookedMethod(SmsHandlerHook.java:55)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.dispatchIntent(<Xposed>)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.dispatchSmsDeliveryIntent(InboundSmsHandler.java:1233)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.-wrap4(Unknown Source:0)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler$CarrierServicesSmsFilterCallback.onFilterComplete(InboundSmsHandler.java:1472)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.android.internal.telephony.CarrierServicesSmsFilter$FilterAggregator.onFilterComplete(CarrierServicesSmsFilter.java:287)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at com.android.internal.telephony.CarrierServicesSmsFilter$CarrierSmsFilterCallback.onFilterComplete(CarrierServicesSmsFilter.java:244)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at android.service.carrier.ICarrierMessagingCallback$Stub.onTransact(ICarrierMessagingCallback.java:55)
08-17 11:25:06.814 E/Xposed  ( 2716): 	at android.os.Binder.execTransact(Binder.java:714)
08-17 11:25:06.816 E/Xposed  ( 2716): NekoSMS: Failed to read preference: pref_whitelist_contacts
08-17 11:25:06.816 E/Xposed  ( 2716): com.crossbowffs.remotepreferences.RemotePreferenceAccessException: query() failed or returned null cursor
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.crossbowffs.remotepreferences.RemotePreferences.query(RemotePreferences.java:156)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.crossbowffs.remotepreferences.RemotePreferences.querySingle(RemotePreferences.java:175)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.crossbowffs.remotepreferences.RemotePreferences.getBoolean(RemotePreferences.java:99)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.getBooleanPref(SmsHandlerHook.java:171)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.beforeDispatchIntentHandler(SmsHandlerHook.java:222)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.access$100(SmsHandlerHook.java:32)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook$DispatchIntentHook.beforeHookedMethod(SmsHandlerHook.java:55)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.dispatchIntent(<Xposed>)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.dispatchSmsDeliveryIntent(InboundSmsHandler.java:1233)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.-wrap4(Unknown Source:0)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler$CarrierServicesSmsFilterCallback.onFilterComplete(InboundSmsHandler.java:1472)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.android.internal.telephony.CarrierServicesSmsFilter$FilterAggregator.onFilterComplete(CarrierServicesSmsFilter.java:287)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at com.android.internal.telephony.CarrierServicesSmsFilter$CarrierSmsFilterCallback.onFilterComplete(CarrierServicesSmsFilter.java:244)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at android.service.carrier.ICarrierMessagingCallback$Stub.onTransact(ICarrierMessagingCallback.java:55)
08-17 11:25:06.816 E/Xposed  ( 2716): 	at android.os.Binder.execTransact(Binder.java:714)
08-17 11:25:06.817 I/Xposed  ( 2716): NekoSMS: Blocking message (matched blacklist)
08-17 11:25:06.818 E/Xposed  ( 2716): NekoSMS: Error occurred in dispatchIntent() hook
08-17 11:25:06.818 E/Xposed  ( 2716): java.lang.IllegalArgumentException: Unknown URL content://com.crossbowffs.nekosms.database/blocked_messages
08-17 11:25:06.818 E/Xposed  ( 2716): 	at android.content.ContentResolver.insert(ContentResolver.java:1585)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.widget.AutoContentLoader.insert(AutoContentLoader.java:90)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.beforeDispatchIntentHandler(SmsHandlerHook.java:239)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.access$100(SmsHandlerHook.java:32)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook$DispatchIntentHook.beforeHookedMethod(SmsHandlerHook.java:55)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.dispatchIntent(<Xposed>)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.dispatchSmsDeliveryIntent(InboundSmsHandler.java:1233)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.-wrap4(Unknown Source:0)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler$CarrierServicesSmsFilterCallback.onFilterComplete(InboundSmsHandler.java:1472)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at com.android.internal.telephony.CarrierServicesSmsFilter$FilterAggregator.onFilterComplete(CarrierServicesSmsFilter.java:287)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at com.android.internal.telephony.CarrierServicesSmsFilter$CarrierSmsFilterCallback.onFilterComplete(CarrierServicesSmsFilter.java:244)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at android.service.carrier.ICarrierMessagingCallback$Stub.onTransact(ICarrierMessagingCallback.java:55)
08-17 11:25:06.818 E/Xposed  ( 2716): 	at android.os.Binder.execTransact(Binder.java:714)
08-17 11:25:06.819 E/Xposed  ( 2716): java.lang.IllegalArgumentException: Unknown URL content://com.crossbowffs.nekosms.database/blocked_messages
08-17 11:25:06.819 E/Xposed  ( 2716): 	at android.content.ContentResolver.insert(ContentResolver.java:1585)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.widget.AutoContentLoader.insert(AutoContentLoader.java:90)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.beforeDispatchIntentHandler(SmsHandlerHook.java:239)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.access$100(SmsHandlerHook.java:32)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook$DispatchIntentHook.beforeHookedMethod(SmsHandlerHook.java:55)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.dispatchIntent(<Xposed>)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.dispatchSmsDeliveryIntent(InboundSmsHandler.java:1233)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler.-wrap4(Unknown Source:0)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at com.android.internal.telephony.InboundSmsHandler$CarrierServicesSmsFilterCallback.onFilterComplete(InboundSmsHandler.java:1472)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at com.android.internal.telephony.CarrierServicesSmsFilter$FilterAggregator.onFilterComplete(CarrierServicesSmsFilter.java:287)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at com.android.internal.telephony.CarrierServicesSmsFilter$CarrierSmsFilterCallback.onFilterComplete(CarrierServicesSmsFilter.java:244)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at android.service.carrier.ICarrierMessagingCallback$Stub.onTransact(ICarrierMessagingCallback.java:55)
08-17 11:25:06.819 E/Xposed  ( 2716): 	at android.os.Binder.execTransact(Binder.java:714)
```

Thank you for helping us help you help us all.

**Comment by apsun** [comment]
I know OxygenOS has a builtin battery saving feature that will disable apps when you are not using them, can you try adding NekoSMS to the whitelist and see if the problem still occurs?

**Comment by WUGqnwvMQPzl** [comment]
It works! Thanks!
