### ISSUE TITLE
希望支持Android Q

### ISSUE THREAD

**Issue by CuCuCheung** [apsun/NekoSMS#60]
Write your issue description here.

---

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device: Pixel 2 XL
- Android version: Android Q DP2
- Xposed version: 
- NekoSMS version: 

Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:

```
Replace this line with your logs. Do not remove the backticks.
```

Thank you for helping us help you help us all.

**Comment by apsun** [comment]
Is there even Xposed for Android Q? NekoSMS does not work without Xposed.

**Comment by chenyue404** [comment]
> Is there even Xposed for Android Q? NekoSMS does not work without Xposed.

Now xposed can run on Android Q

**Comment by kotori2** [comment]
@apsun EdXposed works but it seems NekoSMS doesn't work with Q.
Here are logs.
```
12-03 18:19:20.920  4461  4879 E Xposed  : NekoSMS: Failed to read preference: pref_enable
12-03 18:19:20.920  4461  4879 E Xposed  : com.crossbowffs.remotepreferences.RemotePreferenceAccessException: query() failed or returned null cursor
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.crossbowffs.remotepreferences.RemotePreferences.query(RemotePreferences.java:156)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.crossbowffs.remotepreferences.RemotePreferences.querySingle(RemotePreferences.java:175)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.crossbowffs.remotepreferences.RemotePreferences.getBoolean(RemotePreferences.java:99)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook.getBooleanPref(SmsHandlerHook.java:171)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook.beforeDispatchIntentHandler(SmsHandlerHook.java:202)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook.access$100(SmsHandlerHook.java:32)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook$DispatchIntentHook.beforeHookedMethod(SmsHandlerHook.java:55)
12-03 18:19:20.920  4461  4879 E Xposed  :      at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
12-03 18:19:20.920  4461  4879 E Xposed  :      at EdHooker_.hook(Unknown Source:126)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.android.internal.telephony.InboundSmsHandler.dispatchSmsDeliveryIntent(InboundSmsHandler.java:1356)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.android.internal.telephony.InboundSmsHandler.access$2200(InboundSmsHandler.java:109)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.android.internal.telephony.InboundSmsHandler$CarrierServicesSmsFilterCallback.onFilterComplete(InboundSmsHandler.java:1632)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.android.internal.telephony.CarrierServicesSmsFilter$FilterAggregator.onFilterComplete(CarrierServicesSmsFilter.java:331)
12-03 18:19:20.920  4461  4879 E Xposed  :      at com.android.internal.telephony.CarrierServicesSmsFilter$CarrierSmsFilterCallback.onFilterComplete(CarrierServicesSmsFilter.java:285)
12-03 18:19:20.920  4461  4879 E Xposed  :      at android.service.carrier.ICarrierMessagingCallback$Stub.onTransact(ICarrierMessagingCallback.java:114)
12-03 18:19:20.920  4461  4879 E Xposed  :      at android.os.Binder.execTransactInternal(Binder.java:1032)
12-03 18:19:20.920  4461  4879 E Xposed  :      at android.os.Binder.execTransact(Binder.java:1005)
12-03 18:19:20.923  4461  4879 I Xposed  : NekoSMS: Received a new SMS message
12-03 18:19:20.925  4461  4879 E Xposed  : NekoSMS: Failed to read preference: pref_verbose_logging
12-03 18:19:20.925  4461  4879 E Xposed  : com.crossbowffs.remotepreferences.RemotePreferenceAccessException: query() failed or returned null cursor
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.crossbowffs.remotepreferences.RemotePreferences.query(RemotePreferences.java:156)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.crossbowffs.remotepreferences.RemotePreferences.querySingle(RemotePreferences.java:175)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.crossbowffs.remotepreferences.RemotePreferences.getBoolean(RemotePreferences.java:99)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook.getBooleanPref(SmsHandlerHook.java:171)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook.beforeDispatchIntentHandler(SmsHandlerHook.java:211)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook.access$100(SmsHandlerHook.java:32)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook$DispatchIntentHook.beforeHookedMethod(SmsHandlerHook.java:55)
12-03 18:19:20.925  4461  4879 E Xposed  :      at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
12-03 18:19:20.925  4461  4879 E Xposed  :      at EdHooker_.hook(Unknown Source:126)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.android.internal.telephony.InboundSmsHandler.dispatchSmsDeliveryIntent(InboundSmsHandler.java:1356)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.android.internal.telephony.InboundSmsHandler.access$2200(InboundSmsHandler.java:109)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.android.internal.telephony.InboundSmsHandler$CarrierServicesSmsFilterCallback.onFilterComplete(InboundSmsHandler.java:1632)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.android.internal.telephony.CarrierServicesSmsFilter$FilterAggregator.onFilterComplete(CarrierServicesSmsFilter.java:331)
12-03 18:19:20.925  4461  4879 E Xposed  :      at com.android.internal.telephony.CarrierServicesSmsFilter$CarrierSmsFilterCallback.onFilterComplete(CarrierServicesSmsFilter.java:285)
12-03 18:19:20.925  4461  4879 E Xposed  :      at android.service.carrier.ICarrierMessagingCallback$Stub.onTransact(ICarrierMessagingCallback.java:114)
12-03 18:19:20.925  4461  4879 E Xposed  :      at android.os.Binder.execTransactInternal(Binder.java:1032)
12-03 18:19:20.925  4461  4879 E Xposed  :      at android.os.Binder.execTransact(Binder.java:1005)
12-03 18:19:20.930  4461  4879 E Xposed  : NekoSMS: Failed to read preference: pref_whitelist_contacts
12-03 18:19:20.930  4461  4879 E Xposed  : com.crossbowffs.remotepreferences.RemotePreferenceAccessException: query() failed or returned null cursor
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.crossbowffs.remotepreferences.RemotePreferences.query(RemotePreferences.java:156)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.crossbowffs.remotepreferences.RemotePreferences.querySingle(RemotePreferences.java:175)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.crossbowffs.remotepreferences.RemotePreferences.getBoolean(RemotePreferences.java:99)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook.getBooleanPref(SmsHandlerHook.java:171)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook.beforeDispatchIntentHandler(SmsHandlerHook.java:222)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook.access$100(SmsHandlerHook.java:32)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.crossbowffs.nekosms.xposed.SmsHandlerHook$DispatchIntentHook.beforeHookedMethod(SmsHandlerHook.java:55)
12-03 18:19:20.930  4461  4879 E Xposed  :      at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
12-03 18:19:20.930  4461  4879 E Xposed  :      at EdHooker_.hook(Unknown Source:126)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.android.internal.telephony.InboundSmsHandler.dispatchSmsDeliveryIntent(InboundSmsHandler.java:1356)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.android.internal.telephony.InboundSmsHandler.access$2200(InboundSmsHandler.java:109)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.android.internal.telephony.InboundSmsHandler$CarrierServicesSmsFilterCallback.onFilterComplete(InboundSmsHandler.java:1632)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.android.internal.telephony.CarrierServicesSmsFilter$FilterAggregator.onFilterComplete(CarrierServicesSmsFilter.java:331)
12-03 18:19:20.930  4461  4879 E Xposed  :      at com.android.internal.telephony.CarrierServicesSmsFilter$CarrierSmsFilterCallback.onFilterComplete(CarrierServicesSmsFilter.java:285)
12-03 18:19:20.930  4461  4879 E Xposed  :      at android.service.carrier.ICarrierMessagingCallback$Stub.onTransact(ICarrierMessagingCallback.java:114)
12-03 18:19:20.930  4461  4879 E Xposed  :      at android.os.Binder.execTransactInternal(Binder.java:1032)
12-03 18:19:20.930  4461  4879 E Xposed  :      at android.os.Binder.execTransact(Binder.java:1005)
12-03 18:19:20.930  4461  4879 I Xposed  : NekoSMS: Cached SMS filters dirty, loading from database
12-03 18:19:20.931  4461  4879 E Xposed  : NekoSMS: Failed to load SMS filters (queryAll returned null)
12-03 18:19:20.932  4461  4879 I Xposed  : NekoSMS: Allowing message (filters failed to load)
```

**Comment by apsun** [comment]
@kotori2 those logs generally indicate that the NekoSMS app is frozen/disabled, usually due to battery saver apps.

**Comment by kotori2** [comment]
> @kotori2 those logs generally indicate that the NekoSMS app is frozen/disabled, usually due to battery saver apps.

Thanks. It works fine on Android Q now.

**Comment by Mark2tu** [comment]
> @kotori2 those logs generally indicate that the NekoSMS app is frozen/disabled, usually due to battery saver apps.

Device: Redmi 3S
Android version: Android 10
Xposed version: 90.0-v0.4.6.0_beta(4471) (YAHFA)
NekoSMS version: 0.17.0

Doesn't work with Android 10.
```01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: java.lang.NoSuchMethodError: com.android.internal.telephony.InboundSmsHandler#dispatchIntent(android.content.Intent,java.lang.String,int,android.os.Bundle,android.content.BroadcastReceiver,android.os.UserHandle)#exact
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.hookDispatchIntent23(SmsHandlerHook.java:290)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.hookDispatchIntent(SmsHandlerHook.java:310)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.hookSmsHandler(SmsHandlerHook.java:320)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.handleLoadPackage(SmsHandlerHook.java:337)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:68)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:130)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at android.app.LoadedApk.getResources(LoadedApk.java:1188)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:2462)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:2454)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6343)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:214)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-01 15:50:55.004  2107  2107 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)```
