### ISSUE TITLE
xposed里有错误日志

### ISSUE THREAD

**Issue by 4512369781** [apsun/NekoSMS#65]
Write your issue description here.

---收到短信时，xposed日志里有错误日志。

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device: Nokia 7
- Android version: Android 8.1
- Xposed version: 90-beta3
- NekoSMS version: 0.17.0

Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:

```
12-23 08:37:12.583 I/Xposed  (  684): -----------------
12-23 08:37:12.583 I/Xposed  (  684): Starting Xposed version 90-beta3, compiled for SDK 27
12-23 08:37:12.583 I/Xposed  (  684): Device: TA-1041 (HMD Global), Android version 8.1.0 (SDK 27)
12-23 08:37:12.583 I/Xposed  (  684): ROM: 00CN_2_24G
12-23 08:37:12.583 I/Xposed  (  684): Build fingerprint: Nokia/TA-1041_00CN/C1N:8.1.0/OPR1.170623.026/00CN_2_24G:user/release-keys
12-23 08:37:12.583 I/Xposed  (  684): Platform: arm64-v8a, 64-bit binary, system server: yes
12-23 08:37:12.583 I/Xposed  (  684): SELinux enabled: yes, enforcing: yes
12-23 08:37:12.610 I/Xposed  (  684): -----------------
12-23 08:37:12.610 I/Xposed  (  684): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-22 17:37:30.997 I/Xposed  (  684): Detected ART runtime
11-22 17:37:31.008 I/Xposed  (  684): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-22 17:37:32.559 I/Xposed  (  684): Loading modules from /data/app/bin.xposed.screenshotdelayremover.mod-Lv8fNz1RXjjX6hMSXv8hkg==/base.apk
11-22 17:37:32.610 I/Xposed  (  684):   Loading class bin.xposed.screenshotdelayremover.mod.XposedMod
11-22 17:37:32.612 I/Xposed  (  684): Loading modules from /data/app/com.jozein.xedgepro-ekjQCneot6vIxu2nYbeisA==/base.apk
11-22 17:37:32.678 I/Xposed  (  684):   Loading class com.jozein.xedgepro.xposed.HookMain
11-22 17:37:32.685 I/Xposed  (  684): [XEdgePro] android.system.ErrnoException: stat failed: EACCES (Permission denied)
11-22 17:37:32.744 I/Xposed  (  684): Loading modules from /data/app/ru.oEtSTDLk.PXFvMvjfF-qwEhvj5hEn7BxHRPDzhcgQ==/base.apk
11-22 17:37:32.885 I/Xposed  (  684):   Loading class com.xposed.XSupport
11-22 17:37:32.909 I/Xposed  (  684): Loading modules from /data/app/li.lingfeng.ltweaks-_LDWWHixkrJz207LCJR1MQ==/base.apk
11-22 17:37:33.222 I/Xposed  (  684):   Loading class li.lingfeng.ltweaks.xposed.XposedLoader
11-22 17:37:33.336 I/Xposed  (  684): Loading modules from /data/app/com.flarejune.xposedblacklist-T6TcYVUPTdd_lGXtAt-cOQ==/base.apk
11-22 17:37:33.356 I/Xposed  (  684):   Loading class com.flarejune.xposedblacklist.XposedHook
11-22 17:37:33.363 I/Xposed  (  684): Loading modules from /data/app/com.darkeyes.tricks-KsQ-_esFthOxQOJTEvvk0w==/base.apk
11-22 17:37:33.397 I/Xposed  (  684):   Loading class com.darkeyes.tricks.Main
11-22 17:37:33.400 I/Xposed  (  684): Loading modules from /data/app/com.crossbowffs.nekosms-gc58NQmoQpfVMYfrU3PZEQ==/base.apk
11-22 17:37:33.519 I/Xposed  (  684):   Loading class com.crossbowffs.nekosms.xposed.SmsHandlerHook
11-22 17:37:33.531 I/Xposed  (  684):   Loading class com.crossbowffs.nekosms.xposed.XposedUtilsHook
11-22 17:37:33.531 I/Xposed  (  684): Loading modules from /data/app/xyz.paphonb.androidpify-X2yWZtKMMWqOLAZY8hdt3Q==/base.apk
11-22 17:37:33.735 I/Xposed  (  684):   Loading class xyz.paphonb.androidpify.XposedHook
11-22 17:37:33.760 I/Xposed  (  684): Loading modules from /data/app/com.sudocode.sudohide-pcH8S-qF849ba7epovf8kg==/base.apk
11-22 17:37:33.875 I/Xposed  (  684):   Loading class com.sudocode.sudoHideModule.XposedMain
11-22 17:37:33.892 I/Xposed  (  684): Loading modules from /data/app/ru.timjosten.disablepinripple-e34FkhWj_Ttl8jQapaNR-g==/base.apk
11-22 17:37:33.911 I/Xposed  (  684):   Loading class ru.timjosten.disablepinripple.DisablePINRipple
11-22 17:37:33.912 I/Xposed  (  684): Loading modules from /data/app/github.tornaco.android.thanos-J-TJy7uP_JC5U2bG-P7f3Q==/base.apk
11-22 17:37:34.232 I/Xposed  (  684):   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
11-22 17:37:34.382 I/Xposed  (  684): hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@fafa05b]
11-22 17:37:34.452 I/Xposed  (  684): Loading modules from /data/app/fi.veetipaananen.android.disableflagsecure-eXjzB48Rymn457LCuwHtXQ==/base.apk
11-22 17:37:34.469 I/Xposed  (  684):   Loading class fi.veetipaananen.android.disableflagsecure.DisableFlagSecureModule
11-22 17:37:34.470 I/Xposed  (  684): Loading modules from /data/app/com.ceco.oreo.gravitybox-HjOxzUp93hYJycWe47bIlA==/base.apk
11-22 17:37:34.628 I/Xposed  (  684):   Loading class com.ceco.oreo.gravitybox.GravityBox
11-22 17:37:34.648 I/Xposed  (  684): GB:Hardware: qcom
11-22 17:37:34.648 I/Xposed  (  684): GB:Product: TA-1041_00CN
11-22 17:37:34.648 I/Xposed  (  684): GB:Device manufacturer: HMD Global
11-22 17:37:34.649 I/Xposed  (  684): GB:Device brand: Nokia
11-22 17:37:34.649 I/Xposed  (  684): GB:Device model: TA-1041
11-22 17:37:34.650 I/Xposed  (  684): GB:Device type: phone
11-22 17:37:34.652 I/Xposed  (  684): GB:Is MTK device: false
11-22 17:37:34.652 I/Xposed  (  684): GB:Is Xperia device: false
11-22 17:37:34.652 I/Xposed  (  684): GB:Is Moto XT device: false
11-22 17:37:34.652 I/Xposed  (  684): GB:Is OxygenOS ROM: false
11-22 17:37:34.653 I/Xposed  (  684): GB:Has telephony support: true
11-22 17:37:34.653 I/Xposed  (  684): GB:Has Gemini support: false
11-22 17:37:34.653 I/Xposed  (  684): GB:Android SDK: 27
11-22 17:37:34.653 I/Xposed  (  684): GB:Android Release: 8.1.0
11-22 17:37:34.653 I/Xposed  (  684): GB:ROM: 00CN_2_24G
11-22 17:37:34.653 I/Xposed  (  684): GB:Error logging: false
11-22 17:37:38.584 I/Xposed  (  685): -----------------
11-22 17:37:38.584 I/Xposed  (  685): Starting Xposed version 90-beta3, compiled for SDK 27
11-22 17:37:38.584 I/Xposed  (  685): Device: TA-1041 (HMD Global), Android version 8.1.0 (SDK 27)
11-22 17:37:38.584 I/Xposed  (  685): ROM: 00CN_2_24G
11-22 17:37:38.584 I/Xposed  (  685): Build fingerprint: Nokia/TA-1041_00CN/C1N:8.1.0/OPR1.170623.026/00CN_2_24G:user/release-keys
11-22 17:37:38.584 I/Xposed  (  685): Platform: arm64-v8a, 32-bit binary, system server: no
11-22 17:37:38.584 I/Xposed  (  685): SELinux enabled: yes, enforcing: yes
11-22 17:37:38.587 I/Xposed  (  685): -----------------
11-22 17:37:38.587 I/Xposed  (  685): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-22 17:37:39.812 I/Xposed  (  685): Detected ART runtime
11-22 17:37:39.817 I/Xposed  (  685): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-22 17:37:40.144 I/Xposed  (  685): Loading modules from /data/app/bin.xposed.screenshotdelayremover.mod-Lv8fNz1RXjjX6hMSXv8hkg==/base.apk
11-22 17:37:40.153 I/Xposed  (  685):   Loading class bin.xposed.screenshotdelayremover.mod.XposedMod
11-22 17:37:40.154 I/Xposed  (  685): Loading modules from /data/app/com.jozein.xedgepro-ekjQCneot6vIxu2nYbeisA==/base.apk
11-22 17:37:40.188 I/Xposed  (  685):   Loading class com.jozein.xedgepro.xposed.HookMain
11-22 17:37:40.195 I/Xposed  (  685): [XEdgePro] android.system.ErrnoException: stat failed: EACCES (Permission denied)
11-22 17:37:40.234 I/Xposed  (  685): Loading modules from /data/app/ru.oEtSTDLk.PXFvMvjfF-qwEhvj5hEn7BxHRPDzhcgQ==/base.apk
11-22 17:37:40.355 I/Xposed  (  685):   Loading class com.xposed.XSupport
11-22 17:37:40.379 I/Xposed  (  685): Loading modules from /data/app/li.lingfeng.ltweaks-_LDWWHixkrJz207LCJR1MQ==/base.apk
11-22 17:37:40.671 I/Xposed  (  685):   Loading class li.lingfeng.ltweaks.xposed.XposedLoader
11-22 17:37:40.735 I/Xposed  (  685): Loading modules from /data/app/com.flarejune.xposedblacklist-T6TcYVUPTdd_lGXtAt-cOQ==/base.apk
11-22 17:37:40.745 I/Xposed  (  685):   Loading class com.flarejune.xposedblacklist.XposedHook
11-22 17:37:40.749 I/Xposed  (  685): Loading modules from /data/app/com.darkeyes.tricks-KsQ-_esFthOxQOJTEvvk0w==/base.apk
11-22 17:37:40.759 I/Xposed  (  685):   Loading class com.darkeyes.tricks.Main
11-22 17:37:40.761 I/Xposed  (  685): Loading modules from /data/app/com.crossbowffs.nekosms-gc58NQmoQpfVMYfrU3PZEQ==/base.apk
11-22 17:37:40.842 I/Xposed  (  685):   Loading class com.crossbowffs.nekosms.xposed.SmsHandlerHook
11-22 17:37:40.851 I/Xposed  (  685):   Loading class com.crossbowffs.nekosms.xposed.XposedUtilsHook
11-22 17:37:40.851 I/Xposed  (  685): Loading modules from /data/app/xyz.paphonb.androidpify-X2yWZtKMMWqOLAZY8hdt3Q==/base.apk
11-22 17:37:41.028 I/Xposed  (  685):   Loading class xyz.paphonb.androidpify.XposedHook
11-22 17:37:41.064 I/Xposed  (  685): Loading modules from /data/app/com.sudocode.sudohide-pcH8S-qF849ba7epovf8kg==/base.apk
11-22 17:37:41.170 I/Xposed  (  685):   Loading class com.sudocode.sudoHideModule.XposedMain
11-22 17:37:41.180 I/Xposed  (  685): Loading modules from /data/app/ru.timjosten.disablepinripple-e34FkhWj_Ttl8jQapaNR-g==/base.apk
11-22 17:37:41.193 I/Xposed  (  685):   Loading class ru.timjosten.disablepinripple.DisablePINRipple
11-22 17:37:41.195 I/Xposed  (  685): Loading modules from /data/app/github.tornaco.android.thanos-J-TJy7uP_JC5U2bG-P7f3Q==/base.apk
11-22 17:37:41.428 I/Xposed  (  685):   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
11-22 17:37:41.564 I/Xposed  (  685): hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@610b097]
11-22 17:37:41.570 I/Xposed  (  685): Loading modules from /data/app/fi.veetipaananen.android.disableflagsecure-eXjzB48Rymn457LCuwHtXQ==/base.apk
11-22 17:37:41.580 I/Xposed  (  685):   Loading class fi.veetipaananen.android.disableflagsecure.DisableFlagSecureModule
11-22 17:37:41.585 I/Xposed  (  685): Loading modules from /data/app/com.ceco.oreo.gravitybox-HjOxzUp93hYJycWe47bIlA==/base.apk
11-22 17:37:41.720 I/Xposed  (  685):   Loading class com.ceco.oreo.gravitybox.GravityBox
11-22 17:37:42.634 E/Xposed  ( 2033): Zygote service is not accessible from PID 2033, UID 1000
11-22 17:37:43.114 I/Xposed  ( 2033): GB:Is AOSP forced: true
11-22 17:37:43.299 I/Xposed  ( 2033): [XEdgePro] Xposed edge pro 5.5.1. HMD Global TA-1041, C1N, Android 8.1.0, SDK 27, ROM: 00CN_2_24G, SELinux enforced.
11-22 17:37:43.431 I/Xposed  ( 2033): [XEdgePro] System hooked
11-22 17:37:43.432 I/Xposed  ( 2033): Load li.lingfeng.ltweaks.xposed.system.XposedTextActions for all packages (exclude 1), with prefs []
11-22 17:37:43.436 I/Xposed  ( 2033): Load li.lingfeng.ltweaks.xposed.system.XposedPreventReceiver for android, with prefs []
11-22 17:37:43.441 I/Xposed  ( 2033): Load li.lingfeng.ltweaks.xposed.system.XposedShareFilter for android, with prefs []
11-22 17:37:43.451 I/Xposed  ( 2033): Load li.lingfeng.ltweaks.xposed.system.XposedTrustAgentWifi for android, with prefs []
11-22 17:37:43.458 I/Xposed  ( 2033): Load li.lingfeng.ltweaks.xposed.system.XposedDarkWallpaperColor for android, with prefs [2131755132]
11-22 17:37:43.463 I/Xposed  ( 2033): Load li.lingfeng.ltweaks.xposed.system.XposedPreventWakeLock for android, with prefs []
11-22 17:37:43.464 I/Xposed  ( 2033): Load li.lingfeng.ltweaks.xposed.system.XposedPreventExactAlarm for android, with prefs []
11-22 17:37:43.465 I/Xposed  ( 2033): Load li.lingfeng.ltweaks.xposed.system.XposedSetInactive for android, with prefs []
11-22 17:37:43.465 I/Xposed  ( 2033): Load li.lingfeng.ltweaks.xposed.system.XposedPreventForegroundService for android, with prefs []
11-22 17:37:44.101 I/Xposed  ( 2033): [ThanosS][StringSetRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: clean_up_on_task_removed_pkgs
11-22 17:37:44.120 I/Xposed  ( 2033): [ThanosS][StringSetRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: app_lock_pkgs
11-22 17:37:44.125 I/Xposed  ( 2033): [ThanosS][StringMapRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: component_replacements
11-22 17:37:44.127 I/Xposed  ( 2033): [ThanosS][StringMapRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: priv_device_id
11-22 17:37:44.129 I/Xposed  ( 2033): [ThanosS][StringMapRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: priv_line1_num
11-22 17:37:44.131 I/Xposed  ( 2033): [ThanosS][StringMapRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: priv_sim_num
11-22 17:37:44.142 I/Xposed  ( 2033): [ThanosS][StringSetRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: reminding_ops
11-22 17:37:44.170 I/Xposed  ( 2033): [ThanosS][StringSetRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: screen_on_notification_pkgs
11-22 17:37:48.696 I/Xposed  ( 2033): [XEdgePro] Screen size: 1080, 1920
11-22 17:37:50.111 I/Xposed  ( 2033): WallpaperColors is changed, but keep it black.
11-22 17:37:56.041 I/Xposed  ( 2498): NekoSMS: NekoSMS initializing...
11-22 17:37:56.041 I/Xposed  ( 2498): NekoSMS: Phone manufacturer: HMD Global
11-22 17:37:56.042 I/Xposed  ( 2498): NekoSMS: Phone model: TA-1041
11-22 17:37:56.042 I/Xposed  ( 2498): NekoSMS: Android version: 8.1.0
11-22 17:37:56.042 I/Xposed  ( 2498): NekoSMS: Xposed bridge version: 90
11-22 17:37:56.042 I/Xposed  ( 2498): NekoSMS: NekoSMS version: 0.17.0 (34)
11-22 17:37:56.042 I/Xposed  ( 2498): NekoSMS: Hooking InboundSmsHandler constructor for Android v24+
11-22 17:37:56.045 I/Xposed  ( 2498): NekoSMS: Hooking dispatchIntent() for Android v23+
11-22 17:37:56.047 I/Xposed  ( 2498): NekoSMS: NekoSMS initialization complete!
11-22 17:37:56.059 W/Xposed  ( 2553): useZygotePreferences, but instance exists.
11-22 17:37:56.060 I/Xposed  ( 2553): Load li.lingfeng.ltweaks.xposed.system.XposedAppInfoGoMarket for com.android.settings, with prefs [2131755112]
11-22 17:37:56.106 W/Xposed  ( 2553): useZygotePreferences, but instance exists.
11-22 17:37:56.106 I/Xposed  ( 2553): Load li.lingfeng.ltweaks.xposed.system.XposedAppInfoGoAppData for com.android.settings, with prefs [2131755113]
11-22 17:37:56.120 W/Xposed  ( 2553): useZygotePreferences, but instance exists.
11-22 17:37:56.120 W/Xposed  ( 2553): useZygotePreferences, but instance exists.
11-22 17:37:56.504 I/Xposed  ( 2033): [XEdgePro] Display info{ initial size(1080, 1920), forced size(1080, 1920), initial density=420, scaled density=420 }
11-22 17:37:56.547 I/Xposed  ( 2033): [XEdgePro] Module initialed.
11-22 17:37:56.577 I/Xposed  ( 2498): NekoSMS: Registering SMS filter content observer
11-22 17:37:56.579 I/Xposed  ( 2498): NekoSMS: Registering app package state receiver
11-22 17:37:56.591 I/Xposed  ( 2498): NekoSMS: Checking if we have OP_WRITE_SMS permission
11-22 17:37:56.594 I/Xposed  ( 2498): NekoSMS: Already have OP_WRITE_SMS permission
11-22 18:02:24.015 E/Xposed  ( 2498): NekoSMS: Failed to read preference: pref_enable
11-22 18:02:24.015 E/Xposed  ( 2498): com.crossbowffs.remotepreferences.RemotePreferenceAccessException: query() failed or returned null cursor
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.crossbowffs.remotepreferences.RemotePreferences.query(RemotePreferences.java:156)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.crossbowffs.remotepreferences.RemotePreferences.querySingle(RemotePreferences.java:175)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.crossbowffs.remotepreferences.RemotePreferences.getBoolean(RemotePreferences.java:99)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.getBooleanPref(SmsHandlerHook.java:171)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.beforeDispatchIntentHandler(SmsHandlerHook.java:202)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.access$100(SmsHandlerHook.java:32)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook$DispatchIntentHook.beforeHookedMethod(SmsHandlerHook.java:55)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.android.internal.telephony.InboundSmsHandler.dispatchIntent(<Xposed>)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.android.internal.telephony.InboundSmsHandler.dispatchSmsDeliveryIntent(InboundSmsHandler.java:1283)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.android.internal.telephony.InboundSmsHandler.processMessagePart(InboundSmsHandler.java:1006)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.android.internal.telephony.InboundSmsHandler.-wrap2(Unknown Source:0)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.android.internal.telephony.InboundSmsHandler$DeliveringState.processMessage(InboundSmsHandler.java:471)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:992)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:809)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at android.os.Looper.loop(Looper.java:164)
11-22 18:02:24.015 E/Xposed  ( 2498): 	at android.os.HandlerThread.run(HandlerThread.java:65)
11-22 18:02:24.017 I/Xposed  ( 2498): NekoSMS: Received a new SMS message
11-22 18:02:24.118 I/Xposed  (22323): NekoSMS: Hooking Xposed module status checker
11-22 18:02:24.237 I/Xposed  ( 2498): NekoSMS: Cached SMS filters dirty, loading from database
11-22 18:02:24.261 I/Xposed  ( 2498): NekoSMS: filterCursor.getCount() = 8
11-22 18:02:24.270 I/Xposed  ( 2498): NekoSMS: Loaded 5 blacklist filters
11-22 18:02:24.270 I/Xposed  ( 2498): NekoSMS: Loaded 3 whitelist filters
11-22 18:02:24.279 I/Xposed  ( 2498): NekoSMS: Allowing message (did not match any rules)
```

Thank you for helping us help you help us all.

**Comment by 4512369781** [comment]
是Nokia自带省电管理的问题。
